apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "load-rest-api.fullname" . }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "load-rest-api.selectorLabels" . | nindent 8 }}
  podMetricsEndpoints:
    - targetPort: 9090

